version: 2
updates:
  # Monitor Python dependencies
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 5
    assignees:
      - "emanuelbesliu"
    labels:
      - "dependencies"
      - "python"
    commit-message:
      prefix: "ci(deps)"

  # Monitor GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 5
    assignees:
      - "emanuelbesliu"
    labels:
      - "dependencies"
      - "github-actions"
    commit-message:
      prefix: "ci(deps)"
